### ISSUE TITLE
Some descriptions of guests are missing and missing photos are not always handled the same way

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [programmierbar/website#13]
1. The issue of a guest not having a photo is being addressed in various ways instead of one (I prefer the first way). <br>
![image](https://github.com/programmierbar/website/assets/77451351/a5541fa5-127a-4026-92dd-9116f41364c1)
![image](https://github.com/programmierbar/website/assets/77451351/edcbe0d3-764b-432f-8369-83a76b676b53)

2. It appears that some of the guests do not have a job description listed. <br>
![image](https://github.com/programmierbar/website/assets/77451351/23a944fd-3a44-49f2-aacc-50b394c03047)
![image](https://github.com/programmierbar/website/assets/77451351/63d98350-58a1-44cc-af12-10b862574300)

**Comment by Jan0707** [comment]
Hi @FleetAdmiralJakob thanks for the hint! I have updated the respective profiles accordingly.
