### ISSUE TITLE
Cors error and impressum

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [programmierbar/website#14]
might be only an issue in germany, but if the impressum page is not working you might run into some legal mess.

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://admin.programmier.bar/items/imprint_page.
```

**Comment by Jan0707** [comment]
Thank you for being on the lookout for us!

However, it seems that https://www.programmier.bar/impressum does not throw any kind of error as of today.
Should this re-occur, please re-open this issue with more details.
