### ISSUE TITLE
Add Icon and Link to our Mastodon Instance

### ISSUE THREAD

**Issue by Jan0707** [programmierbar/website#24]
The website footer contains icons/links to all relevant programmier.bar presences outside of the website. With the introduction of our Mastodon account, we should also link out to that.

![Bildschirmfoto 2023-12-29 um 13 55 34](https://github.com/programmierbar/website/assets/1663330/0b904c76-d02a-4987-8c12-28c4a152c388)

**Comment by NJacksonDev** [comment]
Hi, I would like to work on this. Could you please assign this to me?
