### ISSUE TITLE
Iphone 7 search input design bug

### ISSUE THREAD

**Issue by Julian-B90** [programmierbar/website#3]
action:
1. click on the search icon 
2. tip "Ne" and the input switch from round corners to square corners

![IMG_3594](https://user-images.githubusercontent.com/4377396/144724171-dbd89aeb-e5c9-4b61-b043-38f518f84f82.jpg)

**Comment by fabian-hiller** [comment]
Thanks for the tip. I'll investigate the problem and get back to you as soon as it's fixed.

**Comment by fabian-hiller** [comment]
Hey @Julian-B90, I was able to solve the problem. Thanks again for the tip!
