### ISSUE TITLE
Mouse Move→Click→Drag gives link instead of horizontal scroll

### ISSUE THREAD

**Issue by Urfoex** [programmierbar/website#6]
Firefox 94.0.2-1
Chromium 93.0.4577.82-1
Chrome 96.0.4664.93-1

Reproducing: move mouse horizontal, press mouse button down to scroll
Expected: Horizontal scroll
Actual: Mouse "grabs" link, which can be dropped as new tab.

![move-click-drag](https://user-images.githubusercontent.com/1561354/145066944-77c0a06c-458f-4697-861b-3a59b372f396.png)

Afterwards the scroll is also stuck enabled until clicked again.
Also: In Firefox, scrolling seems to stop and gives above occurrence.

**Comment by fabian-hiller** [comment]
Thank you very much for your tip. I am aware of the problem and will investigate it a bit more in the next few days.

**Comment by fabian-hiller** [comment]
Hey @Urfoex the problem should be fixed now. Thank you!
